# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtubedl_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(449, 201)
        self.AppIcon = QtWidgets.QFrame(About)
        self.AppIcon.setGeometry(QtCore.QRect(10, 0, 151, 151))
        self.AppIcon.setAutoFillBackground(False)
        self.AppIcon.setStyleSheet("border-image: url(assets/ytdl.png);")
        self.AppIcon.setFrameShape(QtWidgets.QFrame.Box)
        self.AppIcon.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AppIcon.setObjectName("AppIcon")
        self.Title = QtWidgets.QLabel(About)
        self.Title.setGeometry(QtCore.QRect(170, 10, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.Version = QtWidgets.QLabel(About)
        self.Version.setGeometry(QtCore.QRect(340, 50, 101, 21))
        self.Version.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Version.setObjectName("Version")
        self.OKbt = QtWidgets.QPushButton(About)
        self.OKbt.setGeometry(QtCore.QRect(340, 160, 101, 31))
        self.OKbt.setObjectName("OKbt")
        self.Copyright = QtWidgets.QLabel(About)
        self.Copyright.setGeometry(QtCore.QRect(170, 49, 171, 21))
        self.Copyright.setObjectName("Copyright")
        self.Description = QtWidgets.QLabel(About)
        self.Description.setGeometry(QtCore.QRect(170, 80, 301, 61))
        self.Description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Description.setWordWrap(True)
        self.Description.setObjectName("Description")
        self.Sep1 = QtWidgets.QFrame(About)
        self.Sep1.setGeometry(QtCore.QRect(170, 65, 271, 21))
        self.Sep1.setFrameShape(QtWidgets.QFrame.HLine)
        self.Sep1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Sep1.setObjectName("Sep1")
        self.Sep2 = QtWidgets.QFrame(About)
        self.Sep2.setGeometry(QtCore.QRect(170, 140, 271, 21))
        self.Sep2.setFrameShape(QtWidgets.QFrame.HLine)
        self.Sep2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Sep2.setObjectName("Sep2")
        self.Slogan = QtWidgets.QLabel(About)
        self.Slogan.setGeometry(QtCore.QRect(10, 160, 151, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        self.Slogan.setFont(font)
        self.Slogan.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Slogan.setObjectName("Slogan")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "Form"))
        self.Title.setText(_translate("About", "youtube-dl GUI"))
        self.Version.setText(_translate("About", "Version 1.0.0.0"))
        self.OKbt.setText(_translate("About", "OK"))
        self.Copyright.setText(_translate("About", "Copyright © 2021 MatusGuy"))
        self.Description.setText(_translate("About", "This application downloads a local copy of a YouTube video of your choice. You can also download the video as audio-only for music or sound effects"))
        self.Slogan.setText(_translate("About", "my first professional app\n"
"made for windows"))
import aboutIcon_rc
