# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\SOFTWARE\PythonProjects\youtubedl_GUI_pyqt\interface\addswitches.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdditionalSwitches(object):
    def setupUi(self, AdditionalSwitches):
        AdditionalSwitches.setObjectName("AdditionalSwitches")
        AdditionalSwitches.resize(345, 243)
        AdditionalSwitches.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.gridLayout = QtWidgets.QGridLayout(AdditionalSwitches)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(AdditionalSwitches)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(AdditionalSwitches)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 3, 0, 1, 6)
        self.toolButton_2 = QtWidgets.QToolButton(AdditionalSwitches)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("e:\\SOFTWARE\\PythonProjects\\youtubedl_GUI_pyqt\\interface\\../assets/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 2, 1, 1)
        self.toolButton = QtWidgets.QToolButton(AdditionalSwitches)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("e:\\SOFTWARE\\PythonProjects\\youtubedl_GUI_pyqt\\interface\\../assets/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(AdditionalSwitches)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 5)

        self.retranslateUi(AdditionalSwitches)
        QtCore.QMetaObject.connectSlotsByName(AdditionalSwitches)

    def retranslateUi(self, AdditionalSwitches):
        _translate = QtCore.QCoreApplication.translate
        AdditionalSwitches.setWindowTitle(_translate("AdditionalSwitches", "Dialog"))
        self.label.setText(_translate("AdditionalSwitches", "Aditional switch input:"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("AdditionalSwitches", "aaa"))
        item = self.listWidget.item(1)
        item.setText(_translate("AdditionalSwitches", "bbb"))
        item = self.listWidget.item(2)
        item.setText(_translate("AdditionalSwitches", "ccc"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.toolButton_2.setText(_translate("AdditionalSwitches", "..."))
        self.toolButton.setText(_translate("AdditionalSwitches", "plus"))
