# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cmdlineHelpTextbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cmd(object):
    def setupUi(self, Cmd):
        Cmd.setObjectName("Cmd")
        Cmd.setWindowModality(QtCore.Qt.WindowModal)
        Cmd.resize(750, 620)
        Cmd.setMinimumSize(QtCore.QSize(343, 0))
        Cmd.setMaximumSize(QtCore.QSize(750, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(Cmd)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Text = QtWidgets.QPlainTextEdit(Cmd)
        self.Text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Text.setStyleSheet("background-color: rgb(12, 12, 12);\n"
"color: rgb(204, 204, 204);\n"
"selection-color: rgb(12, 12, 12);\n"
"selection-background-color: rgb(204, 204, 204);\n"
"font: 9pt \"Consolas\";\n"
"\n"
"QScrollBar{\n"
"    color: rgb(255,55,55)\n"
"};")
        self.Text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Text.setReadOnly(True)
        self.Text.setPlainText("")
        self.Text.setObjectName("Text")
        self.gridLayout.addWidget(self.Text, 0, 0, 1, 1)

        self.retranslateUi(Cmd)
        QtCore.QMetaObject.connectSlotsByName(Cmd)

    def retranslateUi(self, Cmd):
        _translate = QtCore.QCoreApplication.translate
        Cmd.setWindowTitle(_translate("Cmd", "Form"))
